### ISSUE TITLE
Wrongly states that I do have node installed 

### ISSUE THREAD

**Issue by mrKappen** [nasa/vscode-pvs#5]

**Comment by pmasci** [comment]
Thank you for reporting the problem.
I have now improved the detection of dependencies in vscode-pvs, please try out the new version
https://github.com/nasa/vscode-pvs/blob/master/releases/

If the problem persists, please check the `Output` panel in vscode, on channel `pvs-server`, which logs information produced during the boot sequence. You should see something like the following:
```
[pvs-server] Checking dependencies...
[pvs-server] node --version
  v12.9.0

[pvs-server] node: v12.9.0
[pvs-language-server] Rebooting PVS (installation folder is /Users/pmasci/Work/pvs-snapshots/pvs-7.1.0)
[pvs-proxy] Activating pvs-proxy...
[pvs-proxy] Rebooting pvs-server...

International Allegro CL Enterprise Edition
10.1 [64-bit Mac OS X (Intel)] (Oct 23, 2020 0:33)
Copyright (C) 1985-2017, Franz Inc., Oakland, CA, USA.  All Rights Reserved.

This dynamic runtime copy of Allegro CL was built by:
   [TC21719] SRI International
```

**Comment by mrKappen** [comment]
Hi @mAp76 Thank you for the quick reply! I am now facing an issue with the extension finding the PVS executables. 
![image](https://user-images.githubusercontent.com/32112423/97057359-0845d900-1559-11eb-9c92-3376fdca171e.png)

**Comment by pmasci** [comment]
Hi, from your output I understand you are using Windows?
I am afraid pvs works only under Linux and MacOS for now -- that's the problem :/

To run vscode-pvs (and pvs) under Windows, you need to create a virtual machine with linux (e.g., Ubuntu) and install/run them in the virtual machine.

**Comment by mrKappen** [comment]
Ah okay. That's too bad. Thanks anyways for all the help. :)
