### ISSUE TITLE
product icon theme contribution is not a real product icon theme

### ISSUE THREAD

**Issue by aeschli** [nasa/vscode-pvs#8]
Product icon themes are a new feature that got final in the upcoming 1.53 release.

I saw that the pvs extension shows up in the list of available product icon themes:
![image](https://user-images.githubusercontent.com/6461412/107051507-d5081c80-67cc-11eb-9f43-2de2e8875ffa.png)

However what the extension [contributes](https://github.com/nasa/vscode-pvs/blob/5c45aa35284d5689e70e88ef3c33aadcdb4c1f7b/vscode-pvs/package.json#L133) is not a real product icon theme (just a file icon theme).
May I suggest to remove the contribution point again to not confuse users?

**Comment by pmasci** [comment]
Thank you for noticing this.

Yes, I will fix that. It's a leftover from some experiments I was doing to understand if there is a way to extend the default vscode icon theme, I must have forgotten to remove it.

**Comment by pmasci** [comment]
Fixed in https://github.com/nasa/vscode-pvs/commit/480f65d1449f11a1363a7550e11666cbcb38362d
